repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Check if all files follow the clippy style
        entry: cargo clippy --fix --allow-staged -- -D warnings
        language: system
        pass_filenames: false
